// This is a placeholder for the service worker
// The actual service worker will be generated by next-pwa

self.addEventListener('install', (event) => {
  console.log('Service Worker installed')
})

self.addEventListener('activate', (event) => {
  console.log('Service Worker activated')
})

self.addEventListener('fetch', (event: any) => {
  // Handle fetch events for offline functionality
  console.log('Fetch event:', event.request.url)
}) 